// BLOCK 1: Constraints
CREATE CONSTRAINT ruiro_id_unique IF NOT EXISTS FOR (n:RuiRo) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT kiemsoat_id_unique IF NOT EXISTS FOR (n:KiemSoat) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT sukien_id_unique IF NOT EXISTS FOR (n:SuKienRuiRo) REQUIRE n.id IS UNIQUE;

// BLOCK: RuiRo nodes
UNWIND [
  {id: 'RR-001', type: 'RuiRo', name: 'Giao dịch chuyển tiền bị hạch toán sai', description: 'Đối soát giao dịch cuối ngày không đầy đủ', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro van hanh', cause: 'Thiếu đối chiếu giữa hệ thống thanh toán và sổ cái', event: 'Giao dịch được ghi nhận sai trạng thái', impact: 'Tổn thất tài chính và khiếu nại khách hàng', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-OPS'},
  {id: 'RR-002', type: 'RuiRo', name: 'Phê duyệt tín dụng vượt thẩm quyền', description: 'Kiểm tra hạn mức phê duyệt không hiệu lực', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro tin dung', cause: 'Phân quyền trên hệ thống không cập nhật', event: 'Khoản vay được phê duyệt vượt thẩm quyền', impact: 'Tăng nợ xấu và vi phạm quy định', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-CREDIT'},
  {id: 'RR-003', type: 'RuiRo', name: 'Giải ngân thiếu hồ sơ bảo đảm', description: 'Hồ sơ giải ngân chưa đủ điều kiện', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro tin dung', cause: 'Kiểm tra điều kiện tiên quyết bị bỏ qua', event: 'Giải ngân khi thiếu chứng từ bắt buộc', impact: 'Khó thu hồi nợ và vi phạm quy trình', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-CREDIT'},
  {id: 'RR-004', type: 'RuiRo', name: 'Lộ thông tin khách hàng', description: 'Quyền truy cập dữ liệu không được kiểm soát phù hợp', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro cong nghe thong tin', cause: 'Cấp quyền vượt nhu cầu công việc', event: 'Dữ liệu khách hàng bị truy cập hoặc chia sẻ trái phép', impact: 'Vi phạm bảo mật và tổn hại uy tín', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-IT'},
  {id: 'RR-005', type: 'RuiRo', name: 'Gián đoạn dịch vụ ngân hàng số', description: 'Hệ thống thanh toán trực tuyến không sẵn sàng', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro cong nghe thong tin', cause: 'Kế hoạch năng lực và dự phòng chưa đầy đủ', event: 'Dịch vụ ngân hàng số bị gián đoạn', impact: 'Mất doanh thu và khiếu nại khách hàng', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-IT'},
  {id: 'RR-006', type: 'RuiRo', name: 'Gian lận giả mạo yêu cầu chuyển tiền', description: 'Nhận diện và xác thực yêu cầu chưa đủ mạnh', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro gian lan', cause: 'Nhân viên không xác minh kênh liên lạc', event: 'Yêu cầu chuyển tiền giả mạo được xử lý', impact: 'Tổn thất tài chính', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-OPS'},
  {id: 'RR-007', type: 'RuiRo', name: 'Chậm báo cáo giao dịch đáng ngờ', description: 'Theo dõi cảnh báo AML không kịp thời', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro tuan thu', cause: 'Khối lượng cảnh báo vượt năng lực xử lý', event: 'Báo cáo giao dịch đáng ngờ nộp muộn', impact: 'Chế tài và rủi ro pháp lý', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-COMPLIANCE'},
  {id: 'RR-008', type: 'RuiRo', name: 'Định giá tài sản bảo đảm không chính xác', description: 'Dữ liệu định giá không độc lập hoặc hết hạn', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro tin dung', cause: 'Thiếu rà soát lại giá trị tài sản', event: 'Tài sản bảo đảm được định giá cao hơn thực tế', impact: 'Tăng tổn thất khi xử lý nợ', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-CREDIT'},
  {id: 'RR-009', type: 'RuiRo', name: 'Không phát hiện giao dịch bất thường', description: 'Luật phát hiện gian lận không được cập nhật', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro gian lan', cause: 'Ngưỡng cảnh báo không phù hợp', event: 'Giao dịch nghi ngờ không bị chặn kịp thời', impact: 'Tổn thất tài chính và uy tín', inherent_level: 'Cao', residual_level: 'Trung binh', owner_unit_id: 'DV-OPS'},
  {id: 'RR-010', type: 'RuiRo', name: 'Sai lệch số liệu báo cáo quản trị', description: 'Dữ liệu nguồn không được đối chiếu', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro bao cao', cause: 'Thay đổi dữ liệu không có kiểm soát', event: 'Báo cáo quản trị có số liệu sai', impact: 'Quyết định quản trị sai lệch', inherent_level: 'Trung binh', residual_level: 'Thap', owner_unit_id: 'DV-FINANCE'},
  {id: 'RR-011', type: 'RuiRo', name: 'Nhà cung cấp công nghệ không đáp ứng cam kết', description: 'Giám sát SLA nhà cung cấp không đầy đủ', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro ben thu ba', cause: 'Điều khoản hợp đồng và chỉ số SLA không được theo dõi', event: 'Dịch vụ thuê ngoài suy giảm chất lượng', impact: 'Gián đoạn dịch vụ và tổn hại uy tín', inherent_level: 'Trung binh', residual_level: 'Trung binh', owner_unit_id: 'DV-IT'},
  {id: 'RR-012', type: 'RuiRo', name: 'Xung đột lợi ích trong mua sắm', description: 'Quy trình lựa chọn nhà cung cấp thiếu độc lập', source_file: 'risk_profiles_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', category: 'Rui ro dao duc', cause: 'Thiếu kê khai và rà soát xung đột lợi ích', event: 'Quyết định mua sắm không khách quan', impact: 'Tăng chi phí và rủi ro pháp lý', inherent_level: 'Trung binh', residual_level: 'Thap', owner_unit_id: 'DV-PROCUREMENT'}
] AS row
MERGE (n:RuiRo {id: row.id}) SET n += row;

// BLOCK: KiemSoat nodes
UNWIND [
  {id: 'KS-001', type: 'KiemSoat', name: 'Đối soát tự động giao dịch và sổ cái', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Detective', frequency: 'Hang ngay', owner_role_id: 'VT-OPS-CONTROL', effectiveness: 'Hieu qua'},
  {id: 'KS-002', type: 'KiemSoat', name: 'Kiểm tra hạn mức phê duyệt trên hệ thống', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Theo giao dich', owner_role_id: 'VT-CREDIT-APPROVER', effectiveness: 'Hieu qua'},
  {id: 'KS-003', type: 'KiemSoat', name: 'Checklist điều kiện giải ngân bắt buộc', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Theo giao dich', owner_role_id: 'VT-CREDIT-OFFICER', effectiveness: 'Can cai thien'},
  {id: 'KS-004', type: 'KiemSoat', name: 'Rà soát quyền truy cập định kỳ', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Hang quy', owner_role_id: 'VT-IT-SECURITY', effectiveness: 'Hieu qua'},
  {id: 'KS-005', type: 'KiemSoat', name: 'Kiểm thử khả năng chịu tải và chuyển đổi dự phòng', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Hang quy', owner_role_id: 'VT-IT-OPERATIONS', effectiveness: 'Can cai thien'},
  {id: 'KS-006', type: 'KiemSoat', name: 'Xác thực hai kênh với lệnh chuyển tiền ngoại lệ', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Theo giao dich', owner_role_id: 'VT-OPS-CONTROL', effectiveness: 'Hieu qua'},
  {id: 'KS-007', type: 'KiemSoat', name: 'Theo dõi SLA xử lý cảnh báo AML', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Detective', frequency: 'Hang ngay', owner_role_id: 'VT-COMPLIANCE-AML', effectiveness: 'Can cai thien'},
  {id: 'KS-008', type: 'KiemSoat', name: 'Rà soát độc lập định giá tài sản bảo đảm', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Detective', frequency: 'Hang nam', owner_role_id: 'VT-CREDIT-REVIEW', effectiveness: 'Hieu qua'},
  {id: 'KS-009', type: 'KiemSoat', name: 'Hiệu chỉnh luật phát hiện giao dịch gian lận', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Preventive', frequency: 'Hang thang', owner_role_id: 'VT-OPS-CONTROL', effectiveness: 'Can cai thien'},
  {id: 'KS-010', type: 'KiemSoat', name: 'Đối chiếu dữ liệu nguồn trước khi phát hành báo cáo', source_file: 'controls_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', control_type: 'Detective', frequency: 'Hang thang', owner_role_id: 'VT-FINANCE-REPORTING', effectiveness: 'Hieu qua'}
] AS row
MERGE (n:KiemSoat {id: row.id}) SET n += row;

// BLOCK: SuKienRuiRo nodes
UNWIND [
  {id: 'SK-001', type: 'SuKienRuiRo', name: 'Sai lệch trạng thái giao dịch được phát hiện khi đối soát cuối ngày', description: 'Sai lệch trạng thái giao dịch được phát hiện khi đối soát cuối ngày', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-001', occurred_at: '2024-03-15', discovered_at: '2024-03-15', severity: 'Trung binh', loss_amount_vnd: '85000000'},
  {id: 'SK-002', type: 'SuKienRuiRo', name: 'Hồ sơ tín dụng được phê duyệt vượt hạn mức của người phê duyệt', description: 'Hồ sơ tín dụng được phê duyệt vượt hạn mức của người phê duyệt', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-002', occurred_at: '2024-04-02', discovered_at: '2024-04-05', severity: 'Cao', loss_amount_vnd: '0'},
  {id: 'SK-003', type: 'SuKienRuiRo', name: 'Giải ngân trước khi hoàn thiện chứng từ bảo đảm', description: 'Giải ngân trước khi hoàn thiện chứng từ bảo đảm', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-003', occurred_at: '2024-04-18', discovered_at: '2024-04-18', severity: 'Cao', loss_amount_vnd: '120000000'},
  {id: 'SK-004', type: 'SuKienRuiRo', name: 'Tài khoản có quyền truy cập dữ liệu vượt phạm vi công việc', description: 'Tài khoản có quyền truy cập dữ liệu vượt phạm vi công việc', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-004', occurred_at: '2024-05-06', discovered_at: '2024-05-07', severity: 'Cao', loss_amount_vnd: '0'},
  {id: 'SK-005', type: 'SuKienRuiRo', name: 'Dịch vụ ngân hàng số gián đoạn trong giờ cao điểm', description: 'Dịch vụ ngân hàng số gián đoạn trong giờ cao điểm', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-005', occurred_at: '2024-05-21', discovered_at: '2024-05-21', severity: 'Cao', loss_amount_vnd: '0'},
  {id: 'SK-006', type: 'SuKienRuiRo', name: 'Yêu cầu chuyển tiền giả mạo được xử lý trước khi bị thu hồi', description: 'Yêu cầu chuyển tiền giả mạo được xử lý trước khi bị thu hồi', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-006', occurred_at: '2024-06-11', discovered_at: '2024-06-11', severity: 'Cao', loss_amount_vnd: '230000000'},
  {id: 'SK-007', type: 'SuKienRuiRo', name: 'Báo cáo giao dịch đáng ngờ nộp quá hạn nội bộ', description: 'Báo cáo giao dịch đáng ngờ nộp quá hạn nội bộ', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-007', occurred_at: '2024-06-28', discovered_at: '2024-07-03', severity: 'Trung binh', loss_amount_vnd: '0'},
  {id: 'SK-008', type: 'SuKienRuiRo', name: 'Rà soát phát hiện giá trị tài sản bảo đảm đã hết hiệu lực', description: 'Rà soát phát hiện giá trị tài sản bảo đảm đã hết hiệu lực', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-008', occurred_at: '2024-07-10', discovered_at: '2024-07-15', severity: 'Cao', loss_amount_vnd: '0'},
  {id: 'SK-009', type: 'SuKienRuiRo', name: 'Giao dịch bất thường chỉ bị phát hiện sau khi khách hàng khiếu nại', description: 'Giao dịch bất thường chỉ bị phát hiện sau khi khách hàng khiếu nại', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-009', occurred_at: '2024-07-22', discovered_at: '2024-07-23', severity: 'Cao', loss_amount_vnd: '175000000'},
  {id: 'SK-010', type: 'SuKienRuiRo', name: 'Báo cáo quản trị sử dụng dữ liệu nguồn chưa đối chiếu', description: 'Báo cáo quản trị sử dụng dữ liệu nguồn chưa đối chiếu', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-010', occurred_at: '2024-08-02', discovered_at: '2024-08-05', severity: 'Trung binh', loss_amount_vnd: '0'},
  {id: 'SK-011', type: 'SuKienRuiRo', name: 'Nhà cung cấp chậm khôi phục dịch vụ so với SLA', description: 'Nhà cung cấp chậm khôi phục dịch vụ so với SLA', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-011', occurred_at: '2024-08-14', discovered_at: '2024-08-14', severity: 'Trung binh', loss_amount_vnd: '0'},
  {id: 'SK-012', type: 'SuKienRuiRo', name: 'Kiểm tra sau mua sắm phát hiện thiếu kê khai xung đột lợi ích', description: 'Kiểm tra sau mua sắm phát hiện thiếu kê khai xung đột lợi ích', source_file: 'risk_events_seed.csv', data_origin: 'SYNTHETIC', verification_status: 'VERIFIED', risk_id: 'RR-012', occurred_at: '2024-09-03', discovered_at: '2024-09-12', severity: 'Trung binh', loss_amount_vnd: '0'}
] AS row
MERGE (n:SuKienRuiRo {id: row.id}) SET n += row;

// BLOCK: MITIGATES relations
UNWIND [
  {source_id: 'KS-001', target_id: 'RR-001', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: đối soát tự động giảm nguy cơ hạch toán sai', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-002', target_id: 'RR-002', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: kiểm tra hạn mức ngăn phê duyệt vượt thẩm quyền', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-003', target_id: 'RR-003', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: checklist ngăn giải ngân thiếu hồ sơ', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-004', target_id: 'RR-004', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: rà soát quyền hạn giảm lộ dữ liệu', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-005', target_id: 'RR-005', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: kiểm thử dự phòng giảm gián đoạn dịch vụ', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-006', target_id: 'RR-006', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: xác thực hai kênh giảm gian lận chuyển tiền', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-007', target_id: 'RR-007', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: theo dõi SLA giảm nguy cơ báo cáo muộn', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-008', target_id: 'RR-008', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: rà soát độc lập giảm sai định giá', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-009', target_id: 'RR-009', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: hiệu chỉnh luật giảm bỏ sót giao dịch bất thường', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'KS-010', target_id: 'RR-010', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: đối chiếu nguồn giảm sai lệch báo cáo', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}}
] AS row
MATCH (a:KiemSoat {id: row.source_id}), (b:RuiRo {id: row.target_id})
MERGE (a)-[r:MITIGATES]->(b) SET r += row.props;

// BLOCK: OBSERVED_AS relations
UNWIND [
  {source_id: 'RR-001', target_id: 'SK-001', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện đối soát giao dịch', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-002', target_id: 'SK-002', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện vượt thẩm quyền', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-003', target_id: 'SK-003', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện giải ngân thiếu hồ sơ', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-004', target_id: 'SK-004', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện quyền truy cập quá mức', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-005', target_id: 'SK-005', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện gián đoạn dịch vụ', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-006', target_id: 'SK-006', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện giả mạo chuyển tiền', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-007', target_id: 'SK-007', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện báo cáo AML muộn', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-008', target_id: 'SK-008', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện sai định giá tài sản', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-009', target_id: 'SK-009', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện không phát hiện bất thường', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-010', target_id: 'SK-010', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện sai lệch báo cáo', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-011', target_id: 'SK-011', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện vi phạm SLA', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}},
  {source_id: 'RR-012', target_id: 'SK-012', props: {source: 'LAB_SEED', evidence_quote: 'Dữ liệu mô phỏng: sự kiện xung đột lợi ích', confidence: '1.0', verification_status: 'VERIFIED', data_origin: 'SYNTHETIC'}}
] AS row
MATCH (a:RuiRo {id: row.source_id}), (b:SuKienRuiRo {id: row.target_id})
MERGE (a)-[r:OBSERVED_AS]->(b) SET r += row.props;

